name: CI - OpenJDK 8 Migration Module

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'openjdk8-migration/**'
      - 'pom.xml'
      - '.github/workflows/ci-openjdk8-migration.yml'
  pull_request:
    branches: [ main, master, develop ]
    types: [opened, synchronize, reopened]
    paths:
      - 'openjdk8-migration/**'
      - 'pom.xml'
      - '.github/workflows/ci-openjdk8-migration.yml'

jobs:
  compile-openjdk8:
    runs-on: ubuntu-latest
    name: Compile OpenJDK 8 Migration Module with OpenJDK 8
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk8-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-jdk8
        
    - name: Verify Java 8 installation
      run: |
        echo "Java version:"
        java -version
        echo "Maven version:"
        mvn --version
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: Enable openjdk8-migration module
      run: |
        echo "Temporarily enabling openjdk8-migration module for compilation..."
        # Uncomment the openjdk8-migration module in parent pom.xml
        sed -i 's|<!-- <module>openjdk8-migration</module> -->|<module>openjdk8-migration</module>|g' pom.xml
        echo "Updated pom.xml modules section:"
        grep -A 10 -B 2 "openjdk8-migration" pom.xml || echo "Module reference not found"
        
    - name: Compile openjdk8-migration module
      run: |
        echo "Compiling openjdk8-migration module with OpenJDK 8..."
        mvn clean compile -pl openjdk8-migration -am -q
        echo "✅ Compilation successful!"
        
    - name: Run tests for openjdk8-migration module
      run: |
        echo "Running tests for openjdk8-migration module..."
        # Note: Some tests may fail due to deprecated APIs - this is expected
        mvn test -pl openjdk8-migration -q || echo "⚠️ Some tests failed (expected for migration demo)"
        
    - name: Package openjdk8-migration module
      run: |
        echo "Packaging openjdk8-migration module..."
        mvn package -pl openjdk8-migration -DskipTests -q
        
    - name: Verify migration examples compile
      run: |
        echo "Verifying that migration examples are properly compiled..."
        find openjdk8-migration/target/classes -name "*.class" | wc -l | xargs echo "Compiled classes:"
        
    - name: List compiled migration examples
      run: |
        echo "Migration example classes found:"
        find openjdk8-migration/target/classes -name "*Example.class" | sed 's|openjdk8-migration/target/classes/||g' | sed 's|/|.|g' | sed 's|.class||g' || echo "No example classes found"
        
    - name: Upload openjdk8-migration artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: openjdk8-migration-artifacts-jdk8
        path: |
          openjdk8-migration/target/*.jar
        retention-days: 7
        
  compile-cross-check:
    runs-on: ubuntu-latest
    name: Cross-compile OpenJDK 8 Migration with OpenJDK 17
    needs: [compile-openjdk8]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Enable openjdk8-migration module
      run: |
        echo "Enabling openjdk8-migration module for cross-compilation check..."
        sed -i 's|<!-- <module>openjdk8-migration</module> -->|<module>openjdk8-migration</module>|g' pom.xml
        
    - name: Cross-compile with JDK 17 targeting JDK 8
      run: |
        echo "Cross-compiling openjdk8-migration with JDK 17 targeting JDK 8..."
        # This will show migration issues - failures are expected and informative
        mvn clean compile -pl openjdk8-migration -Dmaven.compiler.source=8 -Dmaven.compiler.target=8 -q || echo "⚠️ Cross-compilation shows migration issues (expected)"
        
  migration-status:
    runs-on: ubuntu-latest
    needs: [compile-openjdk8, compile-cross-check]
    if: always()
    steps:
    - name: Check OpenJDK 8 migration status
      run: |
        echo "=== OpenJDK 8 Migration Module Status ==="
        echo "JDK 8 Compilation: ${{ needs.compile-openjdk8.result }}"
        echo "JDK 17 Cross-check: ${{ needs.compile-cross-check.result }}"
        
        if [[ "${{ needs.compile-openjdk8.result }}" == "success" ]]; then
          echo "✅ OpenJDK 8 migration module compiles successfully with JDK 8"
          exit 0
        else
          echo "❌ OpenJDK 8 migration module failed to compile with JDK 8"
          exit 1
        fi
